# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
# (and subsequently modified)
#
# Created by: PyQt6 UI code generator (and manual edits)
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Data_Processing(object):
    def setupUi(self, Data_Processing):
        Data_Processing.setObjectName("Data_Processing")
        Data_Processing.setFixedSize(750, 650)  # Slightly increased size for better layout
        font = QtGui.QFont()
        font.setFamily("Calibri")

        self.tabWidget = QtWidgets.QTabWidget(Data_Processing)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 730, 630))
        self.tabWidget.setObjectName("tabWidget")

        # ===================================
        # == Main Processing Tab (Optimized Layout) ==
        # ===================================
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")

        # === 文件输入区域 (File Input Section) ===
        self.fileGroupBox = QtWidgets.QGroupBox(self.mainTab)
        self.fileGroupBox.setGeometry(QtCore.QRect(15, 15, 695, 80))
        font.setPointSize(11)
        font.setBold(True)
        self.fileGroupBox.setFont(font)
        self.fileGroupBox.setTitle("File Input")
        self.fileGroupBox.setStyleSheet("QGroupBox { font-weight: bold; }")
        font.setBold(False)

        # 环的选择
        self.Rings = QtWidgets.QComboBox(self.fileGroupBox)
        self.Rings.setGeometry(QtCore.QRect(15, 25, 120, 35))
        font.setPointSize(11)
        self.Rings.setFont(font)
        self.Rings.setObjectName("Rings")
        items = ["5 Rings", "7 Rings"]
        self.Rings.addItems(items)

        # 数据校准选择
        self.Original = QtWidgets.QComboBox(self.fileGroupBox)
        self.Original.setGeometry(QtCore.QRect(150, 25, 120, 35))
        font.setPointSize(11)
        self.Original.setFont(font)
        self.Original.setObjectName("Original")
        self.Original.addItem("Calibrated")
        self.Original.addItem("Original")

        # 文件路径
        self.Path = QtWidgets.QTextEdit(self.fileGroupBox)
        self.Path.setGeometry(QtCore.QRect(285, 25, 320, 35))
        font.setPointSize(10)
        self.Path.setFont(font)
        self.Path.setObjectName("Path")
        self.Path.setPlaceholderText("Select data file...")

        # 文件选择按钮
        self.FileSelect = QtWidgets.QPushButton(self.fileGroupBox)
        self.FileSelect.setGeometry(QtCore.QRect(615, 25, 70, 35))
        font.setPointSize(11)
        self.FileSelect.setFont(font)
        self.FileSelect.setObjectName("FileSelect")
        self.FileSelect.setText("Browse")

        # === 处理选项区域 (Processing Options Section) ===
        self.optionsGroupBox = QtWidgets.QGroupBox(self.mainTab)
        self.optionsGroupBox.setGeometry(QtCore.QRect(15, 105, 695, 120))
        font.setPointSize(11)
        font.setBold(True)
        self.optionsGroupBox.setFont(font)
        self.optionsGroupBox.setTitle("Processing Options")
        self.optionsGroupBox.setStyleSheet("QGroupBox { font-weight: bold; }")
        font.setBold(False)

        # 第一行选项
        self.TempCheckBox = QtWidgets.QCheckBox(self.optionsGroupBox)
        self.TempCheckBox.setGeometry(QtCore.QRect(20, 30, 120, 25))
        font.setPointSize(11)
        self.TempCheckBox.setFont(font)
        self.TempCheckBox.setChecked(True)
        self.TempCheckBox.setObjectName("TempCheckBox")
        self.TempCheckBox.setText("Temperature")

        self.PLTCheckBox = QtWidgets.QCheckBox(self.optionsGroupBox)
        self.PLTCheckBox.setGeometry(QtCore.QRect(150, 30, 80, 25))
        font.setPointSize(11)
        self.PLTCheckBox.setFont(font)
        self.PLTCheckBox.setChecked(True)
        self.PLTCheckBox.setObjectName("PLTCheckBox")
        self.PLTCheckBox.setText("Plot")

        self.OGTTCheckBox = QtWidgets.QCheckBox(self.optionsGroupBox)
        self.OGTTCheckBox.setGeometry(QtCore.QRect(240, 30, 80, 25))
        font.setPointSize(11)
        self.OGTTCheckBox.setFont(font)
        self.OGTTCheckBox.setChecked(False)
        self.OGTTCheckBox.setObjectName("OGTTCheckBox")
        self.OGTTCheckBox.setText("OGTT")

        self.LDCheckBox = QtWidgets.QCheckBox(self.optionsGroupBox)
        self.LDCheckBox.setGeometry(QtCore.QRect(330, 30, 60, 25))
        font.setPointSize(11)
        self.LDCheckBox.setFont(font)
        self.LDCheckBox.setChecked(False)
        self.LDCheckBox.setObjectName("LDCheckBox")
        self.LDCheckBox.setText("LD")

        # 第二行选项
        self.DyBCCheckBox = QtWidgets.QCheckBox(self.optionsGroupBox)
        self.DyBCCheckBox.setGeometry(QtCore.QRect(20, 65, 140, 25))
        font.setPointSize(11)
        self.DyBCCheckBox.setFont(font)
        self.DyBCCheckBox.setChecked(False)
        self.DyBCCheckBox.setObjectName("DyBCCheckBox")
        self.DyBCCheckBox.setText("Dynamic Basecycle")

        self.expInfoCheckBox = QtWidgets.QCheckBox(self.optionsGroupBox)
        self.expInfoCheckBox.setGeometry(QtCore.QRect(170, 65, 120, 25))
        font.setPointSize(11)
        self.expInfoCheckBox.setFont(font)
        self.expInfoCheckBox.setChecked(False)
        self.expInfoCheckBox.setObjectName("expInfoCheckBox")
        self.expInfoCheckBox.setText("Info for all")

        # 基准周期设置
        self.BaseCycleLabel = QtWidgets.QLabel(self.optionsGroupBox)
        self.BaseCycleLabel.setGeometry(QtCore.QRect(320, 65, 80, 25))
        font.setPointSize(11)
        self.BaseCycleLabel.setFont(font)
        self.BaseCycleLabel.setObjectName("BaseCycleLabel")
        self.BaseCycleLabel.setText("Base Cycle:")

        self.BaseCycle = QtWidgets.QSpinBox(self.optionsGroupBox)
        self.BaseCycle.setGeometry(QtCore.QRect(410, 65, 80, 25))
        font.setPointSize(11)
        self.BaseCycle.setFont(font)
        self.BaseCycle.setMinimum(1)
        self.BaseCycle.setMaximum(99999999)
        self.BaseCycle.setProperty("value", 1)
        self.BaseCycle.setObjectName("BaseCycle")

        # 处理按钮 (右侧独立)
        self.Process = QtWidgets.QPushButton(self.optionsGroupBox)
        self.Process.setGeometry(QtCore.QRect(580, 40, 100, 45))
        font.setPointSize(12)
        font.setBold(True)
        self.Process.setFont(font)
        self.Process.setAutoFillBackground(False)
        self.Process.setStyleSheet("""
            QPushButton {
                color: white;
                background-color: #d32f2f;
                border: none;
                border-radius: 8px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #f44336;
            }
            QPushButton:pressed {
                background-color: #b71c1c;
            }
        """)
        self.Process.setObjectName("Process")
        self.Process.setText("PROCESS")
        font.setBold(False)

        # === 状态显示区域 (Status Section) ===
        self.statusGroupBox = QtWidgets.QGroupBox(self.mainTab)
        self.statusGroupBox.setGeometry(QtCore.QRect(15, 235, 695, 80))
        font.setPointSize(11)
        font.setBold(True)
        self.statusGroupBox.setFont(font)
        self.statusGroupBox.setTitle("Status")
        self.statusGroupBox.setStyleSheet("QGroupBox { font-weight: bold; }")
        font.setBold(False)

        self.StatusLabel = QtWidgets.QLabel(self.statusGroupBox)
        self.StatusLabel.setGeometry(QtCore.QRect(15, 30, 60, 25))
        font.setPointSize(11)
        self.StatusLabel.setFont(font)
        self.StatusLabel.setObjectName("StatusLabel")
        self.StatusLabel.setText("Status:")

        self.Status = QtWidgets.QLineEdit(self.statusGroupBox)
        self.Status.setGeometry(QtCore.QRect(80, 30, 600, 25))
        font.setPointSize(10)
        self.Status.setFont(font)
        self.Status.setObjectName("Status")
        self.Status.setReadOnly(True)
        self.Status.setStyleSheet("background-color: #f5f5f5;")

        # === 错误信息区域 (Error Section) ===
        self.errorGroupBox = QtWidgets.QGroupBox(self.mainTab)
        self.errorGroupBox.setGeometry(QtCore.QRect(15, 325, 695, 120))
        font.setPointSize(11)
        font.setBold(True)
        self.errorGroupBox.setFont(font)
        self.errorGroupBox.setTitle("Error Information")
        self.errorGroupBox.setStyleSheet("QGroupBox { font-weight: bold; }")
        font.setBold(False)

        self.ErrorLabel = QtWidgets.QLabel(self.errorGroupBox)
        self.ErrorLabel.setGeometry(QtCore.QRect(15, 25, 50, 25))
        font.setPointSize(11)
        self.ErrorLabel.setFont(font)
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.ErrorLabel.setText("Error:")

        self.ErrorText = QtWidgets.QTextEdit(self.errorGroupBox)
        self.ErrorText.setGeometry(QtCore.QRect(15, 50, 665, 60))
        font.setPointSize(9)
        self.ErrorText.setFont(font)
        self.ErrorText.setObjectName("ErrorText")
        self.ErrorText.setReadOnly(True)
        self.ErrorText.setStyleSheet("background-color: #fff3e0;")

        self.tabWidget.addTab(self.mainTab, "Processing")

        # ===================================
        # == Plot Configuration Tab ==
        # ===================================
        self.configTab = QtWidgets.QWidget()
        self.configTab.setObjectName("configTab")

        # Use a scroll area for the config tab in case of many options
        self.configScrollArea = QtWidgets.QScrollArea(self.configTab)
        self.configScrollArea.setGeometry(QtCore.QRect(0, 0, 720, 590))  # Adjust to fill tab
        self.configScrollArea.setWidgetResizable(True)
        self.configScrollAreaWidgetContents = QtWidgets.QWidget()
        self.configScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 700, 800))  # Initial large height

        self.configLayout = QtWidgets.QVBoxLayout(
            self.configScrollAreaWidgetContents)  # Main layout for scroll area contents

        # -- Chart Layout Group --
        self.chartLayoutGroup = QtWidgets.QGroupBox("Chart Layout")
        self.chartLayoutGroup.setFont(font)  # Use base font
        self.chartLayoutForm = QtWidgets.QFormLayout()

        _font_form_label = QtGui.QFont();
        _font_form_label.setPointSize(10)

        self.lft_spinbox = QtWidgets.QSpinBox();
        self.lft_spinbox.setRange(0, 5000);
        self.lft_spinbox.setFont(_font_form_label)
        self.chartLayoutForm.addRow(QtWidgets.QLabel("Chart Left (lft):", font=_font_form_label), self.lft_spinbox)

        self.tp_spinbox = QtWidgets.QSpinBox();
        self.tp_spinbox.setRange(0, 5000);
        self.tp_spinbox.setFont(_font_form_label)
        self.chartLayoutForm.addRow(QtWidgets.QLabel("Chart Top (tp):", font=_font_form_label), self.tp_spinbox)

        self.caw_spinbox = QtWidgets.QSpinBox();
        self.caw_spinbox.setRange(100, 5000);
        self.caw_spinbox.setFont(_font_form_label)
        self.chartLayoutForm.addRow(QtWidgets.QLabel("Chart Width (caw):", font=_font_form_label), self.caw_spinbox)

        self.cah_spinbox = QtWidgets.QSpinBox();
        self.cah_spinbox.setRange(100, 5000);
        self.cah_spinbox.setFont(_font_form_label)
        self.chartLayoutForm.addRow(QtWidgets.QLabel("Chart Height (cah):", font=_font_form_label), self.cah_spinbox)

        self.chartLayoutGroup.setLayout(self.chartLayoutForm)
        self.configLayout.addWidget(self.chartLayoutGroup)

        # -- Font Sizes Group --
        self.fontSizesGroup = QtWidgets.QGroupBox("Font Sizes")
        self.fontSizesGroup.setFont(font)
        self.fontSizesForm = QtWidgets.QFormLayout()

        self.ttftsz_spinbox = QtWidgets.QSpinBox();
        self.ttftsz_spinbox.setRange(6, 72);
        self.ttftsz_spinbox.setFont(_font_form_label)
        self.fontSizesForm.addRow(QtWidgets.QLabel("Chart Title (ttftsz):", font=_font_form_label), self.ttftsz_spinbox)

        self.axftsz_spinbox = QtWidgets.QSpinBox();
        self.axftsz_spinbox.setRange(6, 72);
        self.axftsz_spinbox.setFont(_font_form_label)
        self.fontSizesForm.addRow(QtWidgets.QLabel("Axis Labels (axftsz):", font=_font_form_label), self.axftsz_spinbox)

        self.axttftsz_spinbox = QtWidgets.QSpinBox();
        self.axttftsz_spinbox.setRange(6, 72);
        self.axttftsz_spinbox.setFont(_font_form_label)
        self.fontSizesForm.addRow(QtWidgets.QLabel("Axis Title (axttftsz):", font=_font_form_label),
                                  self.axttftsz_spinbox)

        self.gsftsz_spinbox = QtWidgets.QSpinBox();
        self.gsftsz_spinbox.setRange(6, 72);
        self.gsftsz_spinbox.setFont(_font_form_label)
        self.fontSizesForm.addRow(QtWidgets.QLabel("Legend (gsftsz):", font=_font_form_label), self.gsftsz_spinbox)

        self.fontSizesGroup.setLayout(self.fontSizesForm)
        self.configLayout.addWidget(self.fontSizesGroup)

        # -- Marker/Line Styles Group --
        self.markerLineGroup = QtWidgets.QGroupBox("Marker/Line Styles")
        self.markerLineGroup.setFont(font)
        self.markerLineForm = QtWidgets.QFormLayout()

        self.marker_style_combobox = QtWidgets.QComboBox()
        self.marker_styles_map = {
            "Automatic": -4105, "Circle": 8, "Dash": -4115, "Diamond": 2, "Dot": -4118,
            "None": -4142, "Plus": 9, "Square": 1, "Star": 5, "Triangle": 3, "X": -4168
        }
        for name, value in self.marker_styles_map.items():
            self.marker_style_combobox.addItem(name, userData=value)

        self.marker_style_combobox.setFont(_font_form_label)  # xlMarkerStyle constants
        self.markerLineForm.addRow(QtWidgets.QLabel("Series Marker Style:", font=_font_form_label),
                                   self.marker_style_combobox)

        self.marker_size_spinbox = QtWidgets.QSpinBox();
        self.marker_size_spinbox.setRange(1, 20);
        self.marker_size_spinbox.setFont(_font_form_label)
        self.markerLineForm.addRow(QtWidgets.QLabel("Series Marker Size:", font=_font_form_label),
                                   self.marker_size_spinbox)

        self.axis_line_weight_spinbox = QtWidgets.QDoubleSpinBox();
        self.axis_line_weight_spinbox.setRange(0.1, 10.0);
        self.axis_line_weight_spinbox.setSingleStep(0.1);
        self.axis_line_weight_spinbox.setFont(_font_form_label)
        self.markerLineForm.addRow(QtWidgets.QLabel("Axis Line Weight:", font=_font_form_label),
                                   self.axis_line_weight_spinbox)

        self.grid_line_weight_spinbox = QtWidgets.QDoubleSpinBox();
        self.grid_line_weight_spinbox.setRange(0.1, 10.0);
        self.grid_line_weight_spinbox.setSingleStep(0.1);
        self.grid_line_weight_spinbox.setFont(_font_form_label)
        self.markerLineForm.addRow(QtWidgets.QLabel("Grid Line Weight:", font=_font_form_label),
                                   self.grid_line_weight_spinbox)

        self.event_marker_line_weight_spinbox = QtWidgets.QDoubleSpinBox();
        self.event_marker_line_weight_spinbox.setRange(0.1, 10.0);
        self.event_marker_line_weight_spinbox.setSingleStep(0.1);
        self.event_marker_line_weight_spinbox.setFont(_font_form_label)
        self.markerLineForm.addRow(QtWidgets.QLabel("Event Marker Line Weight:", font=_font_form_label),
                                   self.event_marker_line_weight_spinbox)

        self.event_marker_dash_style_combobox = QtWidgets.QComboBox()
        self.dash_styles_map = {
            "Solid": 1, "Dot": -4118, "Dash": -4115, "DashDot": 4, "DashDotDot": 5, "Double": -4119, "SlantDashDot": 13
        }
        for name, value in self.dash_styles_map.items():
            self.event_marker_dash_style_combobox.addItem(name, userData=value)
        self.event_marker_dash_style_combobox.setFont(_font_form_label)  # MsoLineDashStyle constants
        self.markerLineForm.addRow(QtWidgets.QLabel("Event Marker Dash Style:", font=_font_form_label),
                                   self.event_marker_dash_style_combobox)

        self.event_marker_label_size_spinbox = QtWidgets.QSpinBox();
        self.event_marker_label_size_spinbox.setRange(6, 72);
        self.event_marker_label_size_spinbox.setFont(_font_form_label)
        self.markerLineForm.addRow(QtWidgets.QLabel("Event Marker Label Size:", font=_font_form_label),
                                   self.event_marker_label_size_spinbox)

        self.markerLineGroup.setLayout(self.markerLineForm)
        self.configLayout.addWidget(self.markerLineGroup)

        self.configLayout.addStretch()  # Add stretch to push groups to the top
        self.configScrollArea.setWidget(self.configScrollAreaWidgetContents)
        self.tabWidget.addTab(self.configTab, "Plot Configuration")

        # Set initial tab
        self.tabWidget.setCurrentIndex(0)

        self.retranslateUi(Data_Processing)
        QtCore.QMetaObject.connectSlotsByName(Data_Processing)

    def retranslateUi(self, Data_Processing):
        _translate = QtCore.QCoreApplication.translate
        Data_Processing.setWindowTitle(_translate("Data_Processing", "Data Processing Enhanced"))

        # Tab names
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("Data_Processing", "Processing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab),
                                  _translate("Data_Processing", "Plot Configuration"))

        # Group box titles are set in setupUi
        # Config tab group box titles
        self.chartLayoutGroup.setTitle(_translate("Data_Processing", "Chart Layout"))
        self.fontSizesGroup.setTitle(_translate("Data_Processing", "Font Sizes"))
        self.markerLineGroup.setTitle(_translate("Data_Processing", "Marker/Line Styles"))