# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Data_Processing(object):
    def setupUi(self, Data_Processing):
        Data_Processing.setObjectName("Data_Processing")
        # 调整窗口大小以适应GroupBox布局
        Data_Processing.setFixedSize(600, 400)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)

        # ==================== 数据输入组 ====================
        self.dataInputGroup = QtWidgets.QGroupBox(Data_Processing)
        self.dataInputGroup.setGeometry(QtCore.QRect(10, 10, 580, 80))
        self.dataInputGroup.setFont(font)
        self.dataInputGroup.setObjectName("dataInputGroup")

        # 环数选择
        self.Rings = QtWidgets.QComboBox(self.dataInputGroup)
        self.Rings.setGeometry(QtCore.QRect(10, 25, 100, 25))
        self.Rings.setFont(font)
        self.Rings.setObjectName("Rings")
        self.Rings.addItems(["5 Rings", "7 Rings"])

        # 数据类型选择
        self.Original = QtWidgets.QComboBox(self.dataInputGroup)
        self.Original.setGeometry(QtCore.QRect(120, 25, 100, 25))
        self.Original.setFont(font)
        self.Original.setObjectName("Original")
        self.Original.addItem("")
        self.Original.addItem("")

        # 文件路径
        self.Path = QtWidgets.QTextEdit(self.dataInputGroup)
        self.Path.setGeometry(QtCore.QRect(230, 25, 250, 25))
        path_font = QtGui.QFont()
        path_font.setFamily("Calibri")
        path_font.setPointSize(9)
        self.Path.setFont(path_font)
        self.Path.setObjectName("Path")

        # 文件选择按钮
        self.FileSelect = QtWidgets.QPushButton(self.dataInputGroup)
        self.FileSelect.setGeometry(QtCore.QRect(490, 25, 80, 25))
        self.FileSelect.setFont(font)
        self.FileSelect.setObjectName("FileSelect")

        # ==================== 处理选项组 ====================
        self.optionsGroup = QtWidgets.QGroupBox(Data_Processing)
        self.optionsGroup.setGeometry(QtCore.QRect(10, 100, 580, 100))
        self.optionsGroup.setFont(font)
        self.optionsGroup.setObjectName("optionsGroup")

        # 第一行选项
        self.TempCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.TempCheckBox.setGeometry(QtCore.QRect(10, 25, 120, 25))
        self.TempCheckBox.setFont(font)
        self.TempCheckBox.setChecked(True)
        self.TempCheckBox.setObjectName("TempCheckBox")

        self.PLTCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.PLTCheckBox.setGeometry(QtCore.QRect(140, 25, 80, 25))
        self.PLTCheckBox.setFont(font)
        self.PLTCheckBox.setChecked(True)
        self.PLTCheckBox.setObjectName("PLTCheckBox")

        self.OGTTCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.OGTTCheckBox.setGeometry(QtCore.QRect(230, 25, 80, 25))
        self.OGTTCheckBox.setFont(font)
        self.OGTTCheckBox.setChecked(False)
        self.OGTTCheckBox.setObjectName("OGTTCheckBox")

        self.LDCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.LDCheckBox.setGeometry(QtCore.QRect(320, 25, 60, 25))
        self.LDCheckBox.setFont(font)
        self.LDCheckBox.setChecked(False)
        self.LDCheckBox.setObjectName("LDCheckBox")

        # 第二行选项
        self.DyBCCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.DyBCCheckBox.setGeometry(QtCore.QRect(10, 55, 140, 25))
        self.DyBCCheckBox.setFont(font)
        self.DyBCCheckBox.setChecked(False)
        self.DyBCCheckBox.setObjectName("DyBCCheckBox")

        self.expInfoCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.expInfoCheckBox.setGeometry(QtCore.QRect(140, 55, 120, 25))
        self.expInfoCheckBox.setFont(font)
        self.expInfoCheckBox.setChecked(False)
        self.expInfoCheckBox.setObjectName("expInfoCheckBox")

        self.waveDiffCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.waveDiffCheckBox.setGeometry(QtCore.QRect(230, 55, 100, 25))
        self.waveDiffCheckBox.setFont(font)
        self.waveDiffCheckBox.setChecked(False)
        self.waveDiffCheckBox.setObjectName("waveDiffCheckBox")

        self.gradientCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.gradientCheckBox.setGeometry(QtCore.QRect(320, 55, 80, 25))
        self.gradientCheckBox.setFont(font)
        self.gradientCheckBox.setChecked(False)
        self.gradientCheckBox.setObjectName("gradientCheckBox")

        # ==================== 参数设置组 ====================
        self.parametersGroup = QtWidgets.QGroupBox(Data_Processing)
        self.parametersGroup.setGeometry(QtCore.QRect(10, 210, 280, 60))
        self.parametersGroup.setFont(font)
        self.parametersGroup.setObjectName("parametersGroup")

        # 基准周期标签和输入框
        self.BaseCycleLabel = QtWidgets.QLabel(self.parametersGroup)
        self.BaseCycleLabel.setGeometry(QtCore.QRect(10, 25, 80, 25))
        self.BaseCycleLabel.setFont(font)
        self.BaseCycleLabel.setObjectName("BaseCycleLabel")

        self.BaseCycle = QtWidgets.QSpinBox(self.parametersGroup)
        self.BaseCycle.setGeometry(QtCore.QRect(100, 25, 80, 25))
        self.BaseCycle.setFont(font)
        self.BaseCycle.setMinimum(1)
        self.BaseCycle.setMaximum(99999999)
        self.BaseCycle.setProperty("value", 1)
        self.BaseCycle.setObjectName("BaseCycle")

        # ==================== 控制组 ====================
        self.controlGroup = QtWidgets.QGroupBox(Data_Processing)
        self.controlGroup.setGeometry(QtCore.QRect(300, 210, 290, 60))
        self.controlGroup.setFont(font)
        self.controlGroup.setObjectName("controlGroup")

        # 处理按钮
        self.Process = QtWidgets.QPushButton(self.controlGroup)
        self.Process.setGeometry(QtCore.QRect(180, 20, 100, 30))
        process_font = QtGui.QFont()
        process_font.setFamily("Calibri")
        process_font.setPointSize(12)
        process_font.setBold(True)
        self.Process.setFont(process_font)
        self.Process.setStyleSheet("color: rgb(255, 0, 0);")
        self.Process.setObjectName("Process")

        # 状态显示
        self.StatusLabel = QtWidgets.QLabel(self.controlGroup)
        self.StatusLabel.setGeometry(QtCore.QRect(10, 25, 50, 25))
        self.StatusLabel.setFont(font)
        self.StatusLabel.setObjectName("StatusLabel")

        self.Status = QtWidgets.QTextEdit(self.controlGroup)
        # self.Status.setEnabled(False)
        self.Status.setGeometry(QtCore.QRect(65, 25, 110, 25))
        status_font = QtGui.QFont()
        status_font.setFamily("Calibri")
        status_font.setPointSize(9)
        self.Status.setFont(status_font)
        self.Status.setObjectName("Status")

        # ==================== 信息显示组 ====================
        self.infoGroup = QtWidgets.QGroupBox(Data_Processing)
        self.infoGroup.setGeometry(QtCore.QRect(10, 280, 580, 80))
        self.infoGroup.setFont(font)
        self.infoGroup.setObjectName("infoGroup")

        # 错误信息标签和文本框
        self.ErrorLabel = QtWidgets.QLabel(self.infoGroup)
        self.ErrorLabel.setGeometry(QtCore.QRect(10, 25, 50, 25))
        self.ErrorLabel.setFont(font)
        self.ErrorLabel.setObjectName("ErrorLabel")

        self.ErrorText = QtWidgets.QTextEdit(self.infoGroup)
        # self.ErrorText.setEnabled(False)
        self.ErrorText.setGeometry(QtCore.QRect(70, 25, 500, 45))
        error_font = QtGui.QFont()
        error_font.setFamily("Calibri")
        error_font.setPointSize(9)
        self.ErrorText.setFont(error_font)
        self.ErrorText.setObjectName("ErrorText")

        # 设置功能 —— 连接功能区
        self.retranslateUi(Data_Processing)
        QtCore.QMetaObject.connectSlotsByName(Data_Processing)
    
    # 程序自带转译区
    def retranslateUi(self, Data_Processing):
        _translate = QtCore.QCoreApplication.translate
        Data_Processing.setWindowTitle(_translate("Data_Processing", "Data Processing Tool"))

        # GroupBox 标题
        self.dataInputGroup.setTitle(_translate("Data_Processing", "Data Input"))
        self.optionsGroup.setTitle(_translate("Data_Processing", "Processing Options"))
        self.parametersGroup.setTitle(_translate("Data_Processing", "Parameters"))
        self.controlGroup.setTitle(_translate("Data_Processing", "Control"))
        self.infoGroup.setTitle(_translate("Data_Processing", "Information"))

        # 控件文本
        self.Original.setItemText(0, _translate("Data_Processing", "Calibrated"))
        self.Original.setItemText(1, _translate("Data_Processing", "Original"))
        self.FileSelect.setText(_translate("Data_Processing", "Select File"))

        self.TempCheckBox.setText(_translate("Data_Processing", "Temperature"))
        self.PLTCheckBox.setText(_translate("Data_Processing", "Plot"))
        self.OGTTCheckBox.setText(_translate("Data_Processing", "OGTT"))
        self.LDCheckBox.setText(_translate("Data_Processing", "LD"))
        self.DyBCCheckBox.setText(_translate("Data_Processing", "Dynamic Base"))
        self.expInfoCheckBox.setText(_translate("Data_Processing", "Info for All"))
        self.waveDiffCheckBox.setText(_translate("Data_Processing", "1550-1050"))
        self.gradientCheckBox.setText(_translate("Data_Processing", "Gradient"))

        self.BaseCycleLabel.setText(_translate("Data_Processing", "Base Cycle:"))

        self.Process.setText(_translate("Data_Processing", "Process"))
        self.StatusLabel.setText(_translate("Data_Processing", "Status:"))
        self.ErrorLabel.setText(_translate("Data_Processing", "Info:"))
