# .github/workflows/build-python-app.yml

name: Build Python Executable

# 触发条件：
# 1. 当有代码推送到 main 分支时
# 2. 允许在 Actions 页面手动触发此工作流
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    # 指定运行环境为 Windows 最新版
    runs-on: windows-latest

    # 在此处定义环境变量，方便统一修改
    env:
      PYTHON_VERSION: '3.11' # 指定使用的 Python 版本
      MAIN_SCRIPT_PATH: 'data2excel.py' # 您的主程序入口文件（相对路径）
      ICON_PATH: 'favicon01.ico' # 您的图标文件（相对路径）
      OUTPUT_DIR: 'build' # Nuitka 输出目录名
      EXE_NAME: 'data2excel' # 您希望最终生成的 EXE 文件名

    steps:
      # 第一步：检出您的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：生成时间戳，用于 Release 描述
      - name: Generate Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(Get-Date -Format 'yyyyMMdd')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      # 第三步：设置 Python 环境
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 第四步：安装项目依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: cmd

      # 第五步：使用 Nuitka 进行编译
      - name: Build with Nuitka (Compressed Single File)
        run: |
          python -m nuitka --onefile --remove-output --assume-yes-for-downloads ^
            --windows-console-mode=disable ^
            --enable-plugin=pyside6 ^
            --lto=yes ^
            --output-dir=${{ env.OUTPUT_DIR }} ^
            --output-filename=${{ env.EXE_NAME }} ^
            --main=${{ env.MAIN_SCRIPT_PATH }} ^
            --windows-icon-from-ico=${{ env.ICON_PATH }}
        shell: cmd

      # 第六步：创建或更新 Release，并上传正确的文件
      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ env.TIMESTAMP }}"
          name: "Build ${{ env.TIMESTAMP }}"
          body: "This is the latest automated build. Updated at ${{ env.TIMESTAMP }} UTC."
          prerelease: true
          files: ${{ env.OUTPUT_DIR }}/${{ env.EXE_NAME }}.exe
